= CalConnect Standard: Information and documentation -- Bibliographic reference model and serialization

This work item belongs to TC VCARD.

image:https://travis-ci.com/CalConnect/csd-citation-models.svg?branch=master["Build Status", link="https://travis-ci.com/calconnect/csd-citation-models"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-citation-models/[CC/ISO: Information and documentation -- Bibliographic reference model and serialization (HTML)]

== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-citation-models/
----

== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSD XML (https://github.com/calconnect/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open cc-*.html
----

