
[[serialisation]]
[appendix,subtype=informative]
== Reference model XML serialization

The following is a sample serialisation of <<refmodel>> in XML. This is not
intended to be the only
possible serialisation of <<refmodel>>, whether in XML or in another format.
In fact, existing reference tools such as BibTeX <<bibtex>> are
expected to be used as serialisations. The sample serialisation is intended to
provide illustrations
of the model, and to discuss the model succinctly by referencing its elements.
(Of course, the serialisation can be used in practice as a basis for data
exchange of references.)

The serialisation is provided in <<relaxngcompact>>; refer to
<<relaxngcompact_tutorial>> for an introduction to the format.

[[serialisation_rnc]]
[source]
.RELAXNG Compact Serialisation, Reference Model, ISO 690
--

grammar {

# https://www.myintervals.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/
# Somewhat dumbed down for XSD regex:
ISO8601DateTime = xsd:string { pattern = "([\+\-]?\d{4})((-?)((0[1-9]|1[0-2])((-?)([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([\.,]\d+)?)?((:?)[0-5]\d([.,]\d+)?)?([zZ]|([\+\-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?" }
ISO8601Date = xsd:string { pattern = "([\+\-]?\d{4})((-?)((0[1-9]|1[0-2])((-?)([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6]))))?" }

status =
  element status {
     ( stage, substage?, iteration? )
}

stage = element stage { text }
substage = element substage { text }
iteration = element iteration { text }

language = element language { text }
## ISO-639

script = element script { text }
## ISO-15924: Latn

edition = element edition { 
   attribute number { text }?,
   text
}

LocalizedString =
  # multiple languages and scripts possible: comma delimit them if so
  attribute language { text }?,
  attribute script { text }?,
  text 

FormattedString =
  attribute format { ( "text/plain" | "text/html" | "application/docbook+xml" | 
    "application/tei+xml" | "text/x-asciidoc" | "text/markdown" | "application/x-isodoc+xml" | text ) }?,
  LocalizedStringOrXsAny

LocalizedStringOrXsAny =
  # multiple languages and scripts possible: comma delimit them if so
  attribute language { text }?,
  attribute script { text }?,
  ( text | AnyElement )+


contributor = 
  element contributor {
    role*,
    ContributorInfo
}

role =
  element role {
    attribute type { ( "author" | "performer" | "publisher" | "editor" | "adapter" | "translator" | "distributor" ) }?,
    roledescription*
}

ContributorInfo =
  ( person | organization )

roledescription = 
  element description { FormattedString }

person = 
  element person {
    fullname?, affiliation*, person-identifier*, contact*, uri*
}

fullname =
  element name { FullNameType }

FullNameType = 
    (( prefix*, forename*, initial*, surname, addition* ) | completeName ),
    biblionote*, variantname*

prefix = element prefix { LocalizedString }
initial = element initial { LocalizedString }
addition = element addition { LocalizedString }
surname = element surname { LocalizedString }
forename = element forename { LocalizedString }
completeName = element completename { LocalizedString }

variantname = element variant {
  attribute type { text },
  FullNameType
}

affiliation =
  element affiliation { 
    affiliationname?, affiliationdescription*, organization
}

affiliationname = element name { LocalizedString }

affiliationdescription = element description { FormattedString }

organization = 
  element organization {
    orgname, subdivision?, abbreviation?, uri*, org-identifier*, contact*
}

orgname = element name { LocalizedString | NameWithVariants }
subdivision = element subdivision { LocalizedString | NameWithVariants }

NameWithVariants =
  element primary { LocalizedString },
  element variant { NameWithVariants1 }*

NameWithVariants1 =
  attribute type { text },
  element primary { LocalizedString },
  element variant { NameWithVariants1 }*

abbreviation =
  element abbreviation { LocalizedString }

uri =
  element uri { 
    attribute type { text }?,
    xsd:anyURI 
  }

contact =
  ( address | phone | email | uri )

phone = element phone { text }
email = element email { text }

address =
  element address {
    (street+, city, state?, country, postcode? ) | formattedAddress
}

street = element street { text }
city = element city { text }
state = element state { text }
country = element country { text }
postcode = element postcode { text }
formattedAddress = element formattedAddress { text }

person-identifier =
  element identifier {
    attribute type { ("isni" | "uri") },
    text
  }

org-identifier =
  element identifier {
    attribute type { ("orcid" | "uri") },
    text
  }

citation =
  element citation { CitationType }

CitationType = 
    attribute bibitemid { xsd:IDREF },
    locality*, date?

date = element date { ISO8601Date }

locality =
  element locality { BibItemLocality }

BibItemLocality =
    attribute type { LocalityType },
    referenceFrom?, referenceTo?

LocalityType = xsd:string { pattern = "section|clause|part|paragraph|chapter|page|whole|table|annex|figure|note|list|example|volume|issue|time|locality:[a-zA-Z0-9_]+" } 

referenceFrom = element referenceFrom { text }
referenceTo = element referenceTo { text }

bibitem =
  element bibitem { 
     attribute id { xsd:ID },
     BibliographicItem 
}

bibitem_no_id =
  element bibitem { 
     BibliographicItem 
}

relaton_collection = 
  element relaton-collection {
    attribute type { text }?,
    btitle, contributor*,
    docrelation*
}

BibItemType |=
    (  "article" | "book" | "booklet" | "manual" |
       "proceedings" | "presentation" | "thesis" | "techreport" |
       "standard" | "unpublished" | "map" | "electronic resource" | 
       "audiovisual" | "film" | "video" | "broadcast" | "software" |
       "graphic_work" | "music" | "patent" | "inbook" | "incollection" |
        "inproceedings" | "journal" | "website" |"webresource"| "dataset" | "archival" | "misc" )
 
BibliographicItem =
    attribute type { BibItemType }?,
    fetched?,
    (btitle+ | formattedref), bsource*, docidentifier*, docnumber?, bdate*, contributor*,
    edition?, version?, biblionote*, language*, script*,
    abstract*, status?, copyright?, docrelation*, series*, medium?, bplace*, bprice*,
    extent*, accesslocation*, license*, bclassification?, bkeyword*, validity?

btitle = element title { TypedTitleString }
bsource = element uri { TypedUri }
formattedref = element formattedref { FormattedString }
license = element license { text }

fetched = element fetched { ISO8601DateTime }

validity = element validity {
  validityBegins?, validityEnds?, validityRevision?
}
validityBegins = element validityBegins { ISO8601DateTime }
validityEnds = element validityEnds { ISO8601DateTime }
validityRevision = element revision { ISO8601DateTime }


TypedTitleString = 
  attribute type { TitleType }?,
  FormattedString  

TitleType = ( "alternative" | "original" | "unofficial" | "subtitle" | "main" )

TypedUri =
  attribute type { text }?,
  xsd:anyURI 

DateType =
  attribute text { text }?,
  ( ISO8601Date )?

BibliographicDateType =
"published" | "accessed" | "created" | "implemented" | "obsoleted" | "confirmed" | "updated" | "issued" | "transmitted" | "copied" | "unchanged" | "circulated" | "adapted"

bdate = element date {
  attribute type { ( BibliographicDateType | text ) },
  attribute text { text }?,
  (
(
element from { ISO8601Date },
element to { ISO8601Date }?
) |
element on { ISO8601Date }
)?

}

docidentifier = element docidentifier { 
  attribute type { text }?,
  attribute scope { text }?,
  text 
}
docnumber = element docnumber { text }

bclassification = element classification { 
  attribute type { text }?,
  text 
}

bplace = element place { 
  attribute uri { xsd:anyURI }?,
  attribute region { text }?,
  text 
}

bprice = element price {
   attribute currency { text },
   text
}

medium = element medium { 
  content?, form?, carrier?, size?, scale?
}
content = element content { text }
form = element form { text }
carrier = element carrier { text }
size = element size { text }
scale = element scale { text }
accesslocation = element accesslocation { text }

extent = element extent { BibItemLocality }

series = element series {
  attribute type { SeriesType }?,
  (formattedref |
  (btitle, bplace?, seriesorganization?,
  abbreviation?,
  seriesfrom?, seriesto?,
  seriesnumber?, seriespartnumber?, seriesrun?))
}

SeriesType = ( "main" | "alt" )

seriesorganization = element organization { text }
seriesfrom = element from { ISO8601Date }
seriesto = element to { ISO8601Date }
seriesnumber = element number { text }
seriespartnumber = element partnumber { text }
seriesrun = element run { text }

biblionote = element note { 
  attribute type { text }?,
  FormattedString 
}
abstract = element abstract { FormattedString }

copyright =
  element copyright {
    from, to?, owner
}

from = element from { xsd:gYear }
to = element to { xsd:gYear }

owner =
  element owner { ContributorInfo }

DocRelationType =
    "obsoletes" |
    "obsoletedBy" |
    "supersedes" |
    "supersededBy" |
    "updates" |
    "updatedBy" |
    "complements" |
    "derivedFrom" |
    "translatedFrom" |
    "hasTranslation" |
    "adoptedFrom" |
    "equivalent" |
    "identical" |
    "nonequivalent" |
    "includedIn" |
    "includes" |
    "instance" |
    "instanceOf" |
    "partOf" |
    "hasPart" |
    "hasDraft" |
    "draftOf" |
    "merges" |
    "splits" |
    "amends" |
    "amendedBy" |
    "corrects" |
    "correctedBy" |
    "revises" |
    "revisedBy"

docrelation =
  element relation {
    attribute type { DocRelationType },
    element bibitem { BibliographicItem },
    locality*
}

version =
  element version {
    revision-date?, draft*
}

vedition = element edition { xsd:int }
revision-date = element revision-date { ISO8601Date }
draft = element draft { text }

bkeyword = element keyword {
    LocalizedString |
    ( 
       element vocab { LocalizedString },
       vocabid+
    ) |
    ( 
       element taxon { LocalizedString }+,
       vocabid+
    )
}

vocabid = element vocabid {
    attribute type { text },
    attribute uri { xsd:anyURI }?,
    element code { text }?,
    element term { text }?
}

AnyElement = element * { ( text | AnyElement)+ }


}
--
