
[[bibtype]]
== Categories of information resource

* Source: <<iso690,clause 5>>
* Serialisation: `bibitem@type`, `BibItemType`

While <<iso690>> does not prescribe a list of possible bibliographic types,
there are categories specific to particular information resource categories
(<<iso690,clause 5>>),
as well as rendering rules specific to information resource categories (e.g.
<<iso690,clause 5.5>>: series title appears before item title for
broadcasts). For that reason, bibliographic items should indicate what
bibliographic type they belong to.

NOTE: The list of bibliographic types is a union of the types listed in ISO 690
and BibTeX. Master's Thesis and PhD Thesis from BibTeX are subsumed under "thesis".

The list maintains a distinction between the following resources, all of which are
necessarily included in another resource:

"inbook":: A typically untitled part of a book. May be a chapter (or section, etc.) and/or a range of pages.
"incollection":: A part of a book having its own title.
"inproceedings":: An article in a conference proceedings.
"article":: An article from a journal or magazine.

NOTE: The above distinction aligns with BibTeX usage.

The following types have been added:

* dataset: an electronic dataset. Used to avoid the overloading of "electronic resource" as a type.
* webresource: a web resource, a single item accessible online, which is not composed of components 
all of which can be accessed in the same
way. Used to avoid the overloading of "electronic resource" as a type. Includes blog posts, forum posts,
social media posts, tweets, media files, individual web pages.
* website: a collection of web resources. Used to avoid the overloading of "electronic resource" as a type.
* software: computer executable code, not itself human-readable text (though it may generate such text).

