
[[creator]]
== Creator

=== General

* Source: <<iso690,clause 5>>
* Serialisation: `bibitem/contributor`, `Person, Organization, Affiliation`

[[creator-selection]]
=== Selection

<<iso690,clause 5.1>> classifies the various possible roles a creator can have
with regard to a resource into six broad categories in order of priority,
with more refined classifications typically named for the creator. These
classifications
are retained in the model: `bibitem/contributor/role@type` provides the broad
category of role (author, performer, compiler, adaptor, publisher, distributor,
corresponding to <<iso690,clause 5.1.a>> through <<iso690,clause 5.1.f>>), while
`bibitem/contributor/role/description`
contains one or more specific descriptions of the role of the contributor.

The content of the `bibitem/contributor/role` element is optional, and contains
a more specific expression of the creator role. The description can be
strictly a noun, e.g. "librettist", or it can be a phrase, corresponding to how
it will be rendered in a citation ("libretto by"); the choice is at the discretion
of the bibliographer, and is determined by how the citation is expected to be rendered
(as rendering systems are unlikely to be sophisticated enough to convert the one
into the other.)

Whether subsidiary creators should be included in a bibliographic item, and
which creators should be included, is at the discretion of the bibliographer;
see <<iso690,clause 5.4.5>>; <<iso690,clause 5.4.6>>.

Exceptionally, "translator" is differentiated from the other "adaptor" roles of
<<iso690,clause 5.1.d>>, because it is so different to other adaptor roles such
as engraver or photographer.

NOTE: Although both composer and librettist are included as authors under
<<iso690,clause 5.1.a>>, but
the two roles are clearly differentiated in <<iso690,clause 15.8.1>>, with the
composer given priority over the librettist.

NOTE: Inventor and patentee are atypical of the "performer" roles included in
<<iso690,clause 5.1.b>>,
and could arguably be regarded as author roles instead.

NOTE: Sponsoring organisations are conventionally included as distributors,
following practice in <<iso690>>.

====
Ramsey, J. K., & McGrew, W. C. (2005). Object play in great apes: Studies in nature and captivity.
In A. D. Pellegrini & P. K. Smith (Eds.), _The nature of play: Great apes and humans_
(pp. 89-112). New York, NY: Guilford Press.

[source,xml]
--
<bibitem type="incollection">
  <title>Object play in great apes: Studies in nature and captivity</title>
  <date type="published"><on>2005</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Ramsey</surname>
        <initials>J. K.</initials>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>McGrew</surname>
        <initials>W. C.</initials>
      </name>
    </person>
  </contributor>
  <relation type="includedIn">
    <bibitem>
      <title>The nature of play: Great apes and humans</title>
      <contributor>
        <role type="editor"/>
        <person>
          <name>
            <surname>Pellegrini</surname>
            <initials>A. D.</initials>
          </name>
        </person>
      </contributor>
      <contributor>
        <role type="editor"/>
        <person>
          <name>
            <surname>Smith</surname>
            <initials>P. K.</initials>
          </name>
        </person>
      </contributor>
      <contributor>
        <role type="publisher"/>
        <organization>
          <name>Guilford Press</name>
        </organization>
      </contributor>
      <place>New York, NY</place>
    </bibitem>
  </relation>
  <extent type="page">
    <referenceFrom>89</referenceFrom>
    <referenceTo>112</referenceTo>
  </extent>
</bibitem>
--
====

====
Demosthenes. _Speeches 50-59_. Translated from the Greek by
Victor BERS. Austin: University of Texas Press, 2003.

[source,xml]
--
<bibitem type="book">
  <title>Speeches 50-59</title>
  <date type="published"><on>2003</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <completeName>Demosthenes</completeName>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="translator"/>
    <person>
      <name>
        <surname>Bers</surname>
        <initials>Victor</initials>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>University of Texas Press</name>
    </organization>
  </contributor>
  <language>en</language>
  <relation type="translatedFrom">
    <bibitem>
      <title>Speeches 50-59</title>
      <language>grc</language>
    </bibitem>
  </relation>
  <place>Austin</place>
</bibitem>
--
====

====
ROGET, Peter Mark. _Roget's Thesaurus_. Revised by
Susan M. LLOYD. Burnt Mill, Harlow, Essex: Longman Group Limited, 1982 [1852].

[source,xml]
--
<bibitem type="book">
  <title>Roget's Thesaurus</title>
  <date type="created"><on>1852</on></date>
  <date type="updated"><on>1982</on></date>
  <date type="published"><on>1982</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Roget</surname>
        <forename>Peter</forename>
        <forename>Mark</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="editor">revised</role>
    <person>
      <name>
        <surname>Lloyd</surname>
        <forename>Susan</forename>
        <forename>M.</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Longman Group Limited</name>
    </organization>
  </contributor>
  <place>Burnt Mill, Harlow, Essex</place>
</bibitem>
--
====

====
WINSBACHER KNABENCHOR. All' Lust und Freud'. Frankfurt: Bellaphon, 1983.

[source,xml]
--
<bibitem type="audiovisual">
  <title>All' Lust und Freud'</title>
  <date type="published"><on>1983</on></date>
  <contributor>
    <role type="performer"/>
    <organization>
      <name>Winsbacher Knabenchor</name>
    </organization>
  </contributor>
  <contributor>
    <role type="author">composer</role>
    <person><name><completeName>Gastoldi, Giovanni Giacomo</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">composer</role>
    <person><name><completeName>Isaak, Heinrich</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">composer</role>
    <person><name><completeName>Othmayr, Caspar</completeName></name></person>
  </contributor>
  <contributor>
    <role type="author">composer</role>
    <person><name><completeName>Demantius, Christoph</completeName></name></person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bellaphon</name>
    </person>
  </organization>
  <place>Frankfurt</place>
</bibitem>
--
====

=== Personal names

Names may be modelled either broken up into their constituent components
(prefix, forename, initials, surname, addition), or as a complete name string.
The latter is useful if
(contrary to the recommendation of <<iso690,clause 5.2.1>>)
language-specific conventions for ordering of name components are to be
observed; e.g. "James CLARK, John COWAN, MURATA Makoto".

If there are multiple contributors named in a role, all contributors are
expected to be represented in the bibliographic entry.
This reflects practice in electronic bibliographic tools.
The model does contain a representation of "et al.", although renderers may
chose to do so above a certain cutoff point.

The `initials` component is used if all forenames are replaced by initials.
If only the middle name is replaced by an initial, it is still treated as a
forename.

====
BACH, J.S.

[source,xml]
--
<person>
  <name>
    <surname>Bach</surname>
    <initials>J. S.</initials>
  </name>
</person>
--
====

====
PICASSO, Pablo

[source,xml]
--
<person>
  <name>
    <surname>Picasso</surname>
    <forename>Pablo</forename>
  </name>
</person>
--
====

====
KING, Martin Luther, Jr., Rev.

[source,xml]
--
<person>
  <name>
    <prefix>Dr.</prefix>
    <surname>King</surname>
    <forename>Martin</forename>
    <forename>Luther</forename>
    <addition>Jr.</addition>
    <addition>Rev.</addition>
  </name>
</person>
--
====

====
KING, Martin Luther, Jr.

[source,xml]
--
<person>
  <name>
    <completeName>KING, Martin Luther, Jr.</completeName>
  </name>
</person>
--
====

====
STEWART, John H.

[source,xml]
--
<person>
  <name>
    <surname>Stewart</surname>
    <forename>John</forename>
    <forename>H.</forename>
  </name>
</person>
--
====

[[organisation]]
=== Organisations

The model caters for both full names and abbreviations of organisations
(<<iso690,clause 5.3.1>>).
Subordinate body names are modelled separately from the parent body name; the
choice of whether
to model parent + subordinate or a single name depends on the degree of
independence of the subordinate body, as outlined in <<iso690,clause 5.3.3>>.

====
St. Thomas University [Florida].

[source,xml]
--
<organization>
  <name>St. Thomas University [Florida]</name>
</organization>
--
====

====
St. Thomas University [New Brunswick].

[source,xml]
--
<organization>
  <name>St. Thomas University [New Brunswick]</name>
</organization>
--
====

====
ACADEMY OF ATHENS. Research Centre for Modern Greek Dialects.

[source,xml]
--
<organization>
  <name>Academy of Athens</name>
  <subdivision>Research Centre for Modern Greek Dialects</subdivision>
</organization>
--
====

=== Pseudonyms

If both the assumed and the real name of the creator are known, the
supplementary real name (<<iso690,clause 5.5>>) should be modelled as a note.
This follows practice in <<iso690>>, which treats supplementary real names
as annotations, rather than as cross-references.
The model does not currently cater for relations between name instances.

====
TWAIN, Mark [pseud. of Samuel Langhorne CLEMENS]

[source,xml]
--
<person>
  <surname>Twain</surname>
  <forename>Mark</forename>
  <note>pseud. of Samuel Langhorne CLEMENS</note>
</person>
--
====

TODO: Or should we model as a relation between two names? Notes don't have an internal structure,
so can't identify the surname.

=== Anonymous and Varii

Descriptors of authors, such as "Anon" (<<iso690,clause 5.6>>) or
"Various Authors", should be given as completeName
elements. The model does not standardise the designations of
authors. As with pseudonyms, the real name of the creator if known can be
modelled as a note.

====
Anon. _Sir Gawain and the Green Knight_. Edited by R. A. WALDRON. Evanston:
Northwestern University Press, 1970.

[source,xml]
--
<bibitem type="book">
  <title>Sir Gawain and the Green Knight</title>
  <date type="published"><on>1970</on></date>
  <contributor>
    <role type="author"/>
    <person><name><completeName>Anon</completeName></name></person>
  </contributor>
  <contributor>
    <role type="editor"/>
    <person><name><completeName>R. A. WALDRON</completeName></name></person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Northwestern University Press</name>
    </person>
  </organization>
  <place>Evanston</place>
</bibitem>
--
====

====
Anon [Thomas Robert MALTHUS]. _An Essay on the Principle of Population_. 1st edition.
London: J. Johnson, 1798.

[source,xml]
--
<bibitem type="book">
  <title>An Essay on the Principle of Population</title>
  <date type="published"><on>1798</on></date>
  <contributor>
    <role type="author"/>
    <person><name><completeName>Anon</completeName></name></person>
    <note>Thomas Robert MALTHUS</note>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <person><name><completeName>J. Johnson</completeName></name></person>
  </contributor>
  <edition>1st edition</edition>
  <place>London</place>
</bibitem>
--
====

