
[[medium]]
== Medium

* Source: <<iso690,clause 4.4>>, <<iso690,clause 5.4>>
* Serialisation: `bibitem/medium`

<<iso690>> differentiates between the content type of the item,
the media type (which includes file format for electronic media),
the carrier type, the size of the item (which can include duration,
and electronic file size, as well as physical medium size), and
for maps, the scale of the item. These are all
modelled as elements of the item medium; the media type or file format
is modelled as `medium/form`.

There is no fixed vocabulary modelled for any of the elements of `media`
(although <<iso690>> suggests closed Resource Description and Access (RDA)
vocabularies for `medium/content` and `medium/carrier`, and IANA Media Type
is best practice for `medium/form` for electronic resources. As <<iso690>>
allows, there may be instances where the medium descriptions need to be
discursive.

<<iso690>> suggests specifying detailed information about the type of electronic
information resource (e.g. "statistical dataset"); this is modelled as a bibliographical
note (`bibitem/note`), since the type of bibliographic item (`bibite/@type`) is a closed
vocabulary.

Information about alternate formats should be modelled as related bibliographic
items (through the "instance" document relation), each with their own medium information.

The size and scale
of the item usually contains numerical information, but is modelled as a string,
given the complications of how size and scale can be described, particularly for
cartographic material.

====
Sigur Rós.
Untitled [Vaka]. In: _( )_ [compact disc]. Track 1.
Mosfellsbær: Sundlaugin, 2002.

[source,xml]
--
<bibitem type="audiovisual">
  <title>Untitled</title>
  <title type="unofficial">Vaka</title>
  <date type="published"><on>2002</on></date>
  <contributor>
    <role type="author">composer</role>
    <organization><name>Sigur Rós</name></organization>
  </contributor>
  <medium>
    <form>compact disc</form>
  </medium>
  <relation type="includedIn">
    <bibitem>
      <title>( )</title>
      <contributor>
        <role type="author">composer</role>
        <organization><name>Sigur Rós</name></organization>
      </contributor>
      <contributor>
        <role type="publisher"/>
        <organization><name>Sundlaugin</name></organization>
      </contributor>
      <place>Mosfellsbær, Iceland</place>
    </bibitem>
    <locality type="track">
      <referenceFrom>1</referenceFrom>
    </locality>
  </relation>
</bibitem>
--
====

====
Easterbrook, Don J. _Geologic Map of Western Whatcom County, Washington_. Map. 1:62,500. col. 68 x 69 cm. fold. in envelope 30 x 24 cm. Miscellaneous Investigations Series, map 1-854-B. Reston, VA: U.S. Geological Survey, 1976.

[source,xml]
--
<bibitem type="map">
  <title>Geologic Map of Western Whatcom County, Washington</title>
  <date type="published"><on>1976</on></date>
  <contributor>
    <role type="author">
    <person><name><completeName>Easterbrook, Don J.</completeName></name></person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization><name>U.S. Geological Survey</name></organization>
  </contributor>
  <medium>
    <form>map</form>
    <size>col. 68 x 69 cm. fold. in envelope 30 x 24 cm.</size>
    <scale>1:62500</scale>
  </medium>
  <series>
    <title>Miscellaneous Investigations Series</title>
    <number>map 1-854-B</number>
  </series>
  <place>Reston, VA</place>
</bibitem>
--

====

