
[[edition]]
== Edition

* Source: <<iso690,clause 8>>
* Serialisation: `bibitem/edition, bibitem/date`

Editions are modelled as free text, given the variety of ways they can be represented
(<<iso690,clause 8.1>>).
For that reason, the full word "edition" needs to appear after any ordinal.

Dates when a resource was last accessed are modelled as `date[@type = "accessed"]`;
dates when a resource was last updated are modelled as `date[@type = "updated"]`
(<<iso690,clause 8.2>>).

====
Anon [Thomas Robert MALTHUS]. _An Essay on the Principle of Population_. 1st edition.
London: J. Johnson, 1798.

[source,xml]
--
<bibitem type="book">
  <title>An Essay on the Principle of Population</title>
  <date type="published"><on>1798</on></date>
  <contributor>
    <role type="author"/>
    <person><name><completeName>Anon</completeName></name></person>
    <note>Thomas Robert MALTHUS</note>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <person><name><completeName>J. Johnson</completeName></name></person>
  </contributor>
  <edition>1st edition</edition>
  <place>London</place>
</bibitem>
--
====

====
SKOUSEN, Mark. _The Structure of Production_. New revised edition.
New York: New York University Press, 2015.

[source,xml]
--
<bibitem type="book">
  <title>The Structure of Production</title>
  <date type="published"><on>2015</on></date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname>Skousen</surname>
        <forename>Mark</forename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization><name>New York University Press</name></organization>
  </contributor>
  <edition>New revised edition</edition>
  <place>New York</place>
</bibitem>
--
====

====
When did the sounds of 'w' and 'v' change in High German?
_Stack Exchange: Linguistics Beta_.
Updated 10 May 2017 [viewed 8 May 2018].
Available from: https://linguistics.stackexchange.com/questions/22872/when-did-the-sounds-of-w-and-v-change-in-high-german

[source,xml]
--
<bibitem type="electronic resource">
  <title>When did the sounds of 'w' and 'v' change in High German?</title>
  <link>https://linguistics.stackexchange.com/questions/22872/when-did-the-sounds-of-w-and-v-change-in-high-german</link>
  <date type="updated"><on>2017-05-10</on></date>
  <date type="accessed"><on>2018-05-08</on></date>
  <relation type="includedIn">
    <bibitem>
      <title>Stack Exchange: Linguistics Beta</title>
    </bibitem>
  </relation>
</bibitem>
--
====
